[package]
name = "cond"
version = "1.0.0"
authors = ["CheckM4te", "github.com/Esper89"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
